<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <StartupObject>TestConsole.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TestCases.Runtime\TestCases.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Shouldly" Version="4.3.0" />
  </ItemGroup>

</Project>
